import json
import os
import re

from .common import InfoExtractor
from ..utils import ass_subtitles_timecode, float_or_none, str_or_none, traverse_obj, url_or_none


class LividIE(InfoExtractor):
    _VALID_URL = r'https?://(?:www\.)?livid\.com/(?:watch|embed)/(?P<id>[0-9A-Za-z]+)'
    _TESTS = [{
        'url': 'https://livid.com/watch/J09eQruc7E6u',
        'info_dict': {
            'id': 'J09eQruc7E6u',
            'ext': 'mp4',
            'title': 'Livid Analytics',
            'description': 'md5:d9379f9311b79078eaeec6b228f5e8f6',
            'thumbnail': r're:https?://api\.livid\.com/v1/thumbnails/.*\.jpg$',
            'uploader_id': 'f0d8c8430a7340b09355e9c9ca629afd',
            'duration': 19,
            'timestamp': 1774525149,
            'upload_date': '20260326',
        },
        'params': {
            'skip_download': True,
        },
    }, {
        'url': 'https://livid.com/embed/lDlnp0fM1omO',
        'md5': 'e6736151653f657b4d7069a77f7cd716',
        'info_dict': {
            'id': 'lDlnp0fM1omO',
            'ext': 'mp4',
            'title': 'youtube-dl test video ＂\'⧸⧹ä↭𝕐 [BaW_jenozKc]',
            'description': 'md5:ebb3481475b337bdffae01644f2f9280',
            'thumbnail': r're:https?://api\.livid\.com/v1/thumbnails/.*\.jpg$',
            'uploader_id': '9eebf39a8c1d43819626b266e718a445',
        },
        'params': {
            'skip_download': True,
        },
    }]

    def _get_subtitles(self, uuid: str, transcripts: dict, video_id: str) -> dict[str, list[dict]]:
        subtitles = {}
        for transcript in transcripts.get('transcripts', []):
            if transcript.get('source') == 'auto':
                continue
            language = traverse_obj(transcript, ('language', {str_or_none}))
            segments = traverse_obj(
                self._download_json(f'https://api.livid.com/v1/videos/id/{uuid}/transcript-segments?language={language}', video_id),
                ('segments', {list}))
            if segments is None:
                continue
            if language == 'unknown':
                language = 'und'
            subtitles[language] = [
                {'ext': 'json', 'data': json.dumps(segments)},
                {'ext': 'ass', 'data': self._generate_ass_subtitles(segments)},
            ]
        return subtitles

    def _get_automatic_captions(self, uuid: str, transcripts: dict, video_id: str) -> dict[str, list[dict]]:
        captions = {}
        for transcript in transcripts.get('transcripts', []):
            if transcript.get('source') != 'auto':
                continue
            language = traverse_obj(transcript, ('language', {str_or_none}))
            segments = traverse_obj(
                self._download_json(f'https://api.livid.com/v1/videos/id/{uuid}/transcript-segments?language={language}', video_id),
                ('segments', {list}))
            if segments is None:
                continue
            if language == 'unknown':
                language = 'und'
            captions[language] = [
                {'ext': 'json', 'data': json.dumps(segments)},
                {'ext': 'ass', 'data': self._generate_ass_subtitles(segments)},
            ]
        return captions

    def _generate_ass_subtitles(self, segments: list[dict[str, float | str]]):
        ass = f'''[Script Info]
; Script generated by `{self.__class__.__module__}.{self.__class__.__qualname__}`
ScriptType: v4.00+
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'''
        for segment in segments:
            start, end, text = (
                float_or_none(segment.get('start')),
                float_or_none(segment.get('end')),
                str_or_none(segment.get('text')))
            if start is None or end is None or text is None:
                continue
            ass += os.linesep + f'Dialogue: Marked=0,{ass_subtitles_timecode(start)},{ass_subtitles_timecode(end)},Default,,0,0,0,,{text}'
        return ass

    def _real_extract(self, url):
        video_id = self._match_id(url)
        webpage = self._download_webpage(url, video_id)

        title = self._generic_title(url, webpage)
        description = self._html_search_meta(['description', 'og:description', 'twitter:description'], webpage)
        m3u8_url = self._search_regex(r'src\s*:\s*(["\'])(?P<url>[^"\']*m3u8)\1', webpage, 'source', group='url')
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(m3u8_url, video_id)
        for liste in subtitles.values():
            for sub_dict in liste:
                sub_dict.setdefault('id', video_id)
        uploader_id = self._search_regex(r'organizationId\s*:\s*(["\'])(?P<uploader_id>[^"\']*)\1',
                                         webpage, 'uploader id', default=None, group='uploader_id')
        small_thumbnail = self._search_regex(r'srcSmall\s*:\s*(["\'])(?P<url>[^"\']*)\1', webpage, 'source', group='url')
        json_ld = self._search_json_ld(webpage, video_id, fatal=False, default={})
        uuid = traverse_obj(re.findall(r'id\s*:\s*(["\'])(?P<id>[^"\']*)\1', webpage), (2, 1))
        transcripts = self._download_json(f'https://api.livid.com/v1/videos/id/{uuid}/transcripts', video_id) or {}

        subs2 = self.extract_subtitles(uuid, transcripts, video_id)
        for lang, value in subs2.items():
            subtitles.setdefault(lang, []).extend(value)

        return {
            'id': video_id,
            **json_ld,
            'title': title,
            'description': description,
            'thumbnails': [
                {'url': url_or_none(self._og_search_thumbnail(webpage))},
                {'url': small_thumbnail, 'preference': -2},
            ],
            'formats': formats,
            'subtitles': subtitles,
            'automatic_captions': self.extract_automatic_captions(uuid, transcripts, video_id),
            'uploader_id': uploader_id,
        }
